#! /usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

rm -f $HOME/.ideavimrc
ln -s $DOTFILES/idea/vimrc $HOME/.ideavimrc

rm -rf $HOME/.config/wezterm
ln -s $DOTFILES/wezterm $HOME/.config/wezterm

rm -f $HOME/.zshrc
ln -s $DOTFILES/zsh/zshrc $HOME/.zshrc
